In [2]:
import numpy as np
from scipy import linalg

A = np.array([[-1, 1, 0], [-4, 3, 0], [1, 0, 2]])  #定义矩阵
eigenvalues, eigenvectors = linalg.eig(A)  #使用linalg模块中的eig()函数求数值解
print("特征值:", eigenvalues)
print("特征向量:")
print(eigenvectors)



特征值: [2.+0.j 1.+0.j 1.+0.j]
特征向量:
[[ 0.          0.40824829  0.40824829]
 [ 0.          0.81649658  0.81649658]
 [ 1.         -0.40824829 -0.40824829]]


In [3]:
import numpy as np
from scipy import linalg
import sympy as sp

a = sp.Matrix([[-1, 1, 0], [-4, 3, 0], [1, 0, 2]])
print('特征值为：', a.eigenvals())
print('特征向量为：\n', a.eigenvects())#符号解

特征值为： {1: 2, 2: 1}
特征向量为：
 [(1, 2, [Matrix([
[-1],
[-2],
[ 1]])]), (2, 1, [Matrix([
[0],
[0],
[1]])])]
