In [37]:
import numpy as np
from scipy.optimize import fsolve , root
import sympy as sp
def f(x):
    return (np.abs(x+1)-np.abs(x-1))/2+np.sin(x)
def g(x):
    return (np.abs(x+3)-np.abs(x-3))/2+np.cos(x)

In [38]:
fx = lambda x :[3*f(x[2])+4*g(x[3])-1-2*x[0],2*f(x[2])+6*g(x[3])-2-3*x[1],f(x[0])+3*g(x[1])-3-x[2]-5*x[3],4*f(x[0])+6*g(x[1])-1-5*x[3]]

In [39]:
sol1 = fsolve(fx,[1,0,0,0])
sol1

array([-0.85941162,  0.25135985, -0.80919433, -0.0295742 ])

In [40]:
sol2 = root (fx,[0,0,0,0])
sol2

 message: The solution converged.
 success: True
  status: 1
     fun: [ 6.526e-11  4.773e-11 -1.736e-12 -5.973e-11]
       x: [-8.594e-01  2.514e-01 -8.092e-01 -2.957e-02]
    nfev: 13
    fjac: [[-2.932e-01 -1.031e-03  2.219e-01  9.300e-01]
           [ 4.526e-01 -7.998e-01  3.913e-01  4.843e-02]
           [-8.383e-01 -4.677e-01  4.784e-02 -2.762e-01]
           [-8.067e-02  3.762e-01  8.918e-01 -2.378e-01]]
       r: [ 6.807e+00  5.264e+00 -1.686e+00 -7.581e+00  3.625e+00
           -7.911e-01 -5.409e+00 -5.929e+00 -4.898e+00 -1.490e+00]
     qtf: [-2.572e-08 -4.481e-09 -1.373e-08  4.982e-09]

In [42]:
print(sol1,'/n','---------')
print(sol2)

[-0.85941162  0.25135985 -0.80919433 -0.0295742 ] /n ---------
 message: The solution converged.
 success: True
  status: 1
     fun: [ 6.526e-11  4.773e-11 -1.736e-12 -5.973e-11]
       x: [-8.594e-01  2.514e-01 -8.092e-01 -2.957e-02]
    nfev: 13
    fjac: [[-2.932e-01 -1.031e-03  2.219e-01  9.300e-01]
           [ 4.526e-01 -7.998e-01  3.913e-01  4.843e-02]
           [-8.383e-01 -4.677e-01  4.784e-02 -2.762e-01]
           [-8.067e-02  3.762e-01  8.918e-01 -2.378e-01]]
       r: [ 6.807e+00  5.264e+00 -1.686e+00 -7.581e+00  3.625e+00
           -7.911e-01 -5.409e+00 -5.929e+00 -4.898e+00 -1.490e+00]
     qtf: [-2.572e-08 -4.481e-09 -1.373e-08  4.982e-09]
