In [1]:
import numpy as np
from scipy.optimize import least_squares


In [2]:
#定义f(x),g(x)函数
def f(x):
    return (np.abs(x+1)-np.abs(x-1))/2+np.sin(x)

def g(x):
    return (np.abs(x+3)-np.abs(x-3))/2+np.cos(x)


In [3]:
fx = lambda x: [
    3*f(x[2]) + 4*g(x[3]) - 1 - 2*x[0],
    2*f(x[2]) + 6*g(x[3]) - 2 - 3*x[1],
    f(x[0]) + 3*g(x[1]) - 3 - x[2] - 5*x[3],
    4*f(x[0])+6*g(x[1])-1-5*x[3],
    f(x[3])+g(x[3])-2-x[0]-x[0],
    2*f(x[0])-10*g(x[2])-5-x[1]+3*x[3]
]


In [4]:
result = least_squares(fx, np.array([1, 0, 1, 1]))
result


     message: `ftol` termination condition is satisfied.
     success: True
      status: 2
         fun: [-7.994e-01  1.132e-02 -1.577e-01  7.737e-02  8.608e-01
               -4.035e-02]
           x: [-7.534e-01  2.763e-01 -1.167e+00  1.205e-01]
        cost: 0.7063074521159828
         jac: [[-2.000e+00  0.000e+00  1.178e+00  3.519e+00]
               [-0.000e+00 -3.000e+00  7.850e-01  5.279e+00]
               ...
               [-2.000e+00  0.000e+00 -0.000e+00  2.873e+00]
               [ 3.459e+00 -1.000e+00 -1.920e+01  3.000e+00]]
        grad: [-1.226e-07 -2.028e-07  3.407e-06 -3.664e-05]
  optimality: 3.664122367030842e-05
 active_mask: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00]
        nfev: 9
        njev: 9